### ISSUE TITLE
[prod] Fix "Mixed Content" browser warnings

### ISSUE THREAD

**Issue by jakubgs** [dap-ps/infra-dapps#12]
We are getting warnings like this:
```
Mixed Content: The page at 'https://dev.dap.ps/' was loaded over HTTPS, but requested an insecure image 
'http://dev.dap.ps/metadata/image/QmPYrsnabEESX8w9xrmsW71DH1jgpJegj52gZanWZzDmr3'. 
This content should also be served over HTTPS.
```

**Comment by jakubgs** [comment]
As far as I know the issue is with the `react-image-fallback` and how it's used, for example in `Vote`:
```jsx
<ReactImageFallback
  className={styles.image}
  src={dapp.image}
  fallbackImage={icon}
  alt="App icon"
  width={24}
  height={24}
/>
```
https://github.com/dap-ps/discover/blob/6dd2282a2c982fe64565fb7bb9c00431fdc382c4/src/modules/Vote/Vote.jsx#L129-L136

As far as I can tell the value of `dapp.image` the thing that causes the HTTP requests.

**Comment by jakubgs** [comment]
This `dapp.image` comes from the `DappModel` class:
```javascript
export default class DappModel {
  constructor() {
    // blockchain
    this.id = ''
    this.sntValue = 0

    // metadata
    this.email = ''
    this.name = ''
    this.image = ''
...
```
https://github.com/dap-ps/discover/blob/6dd2282a2c982fe64565fb7bb9c00431fdc382c4/src/common/data/dapp.js#L3-L17

**Comment by jakubgs** [comment]
This model is apparently used with the [`idb`](https://www.npmjs.com/package/idb) package, which "mirrors the IndexedDB API".
```javascript
export default class Database {
  static async fetchAllDapps() {
    const result = []
    const db = await open()
    let cursor = await db.transaction(DB_STORE_DAPPS).store.openCursor()

    while (cursor) {
      result.push(Object.assign(new DappModel(), cursor.value))
      cursor = await cursor.continue()
    }
    return result
  }
...
```
https://github.com/dap-ps/discover/blob/6dd2282a2c982fe64565fb7bb9c00431fdc382c4/src/common/data/database.js#L21-L26

**Comment by jakubgs** [comment]
And "IndexedDB" is apparently:

>low-level API for client-side storage of significant amounts of structured data, including files/blobs

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

And this can be looked up using the "Application" tab of the Chrome dev console:
![dev_dap_ps_indexed_db](https://user-images.githubusercontent.com/2212681/62641845-81382100-b912-11e9-8b1e-0da89219d125.png)

We can see here that the URLs do indeed use `http`.

**Comment by jakubgs** [comment]
Deleting this database using the dev console does not help:
![deleting_indexed_db](https://user-images.githubusercontent.com/2212681/62641990-c6f4e980-b912-11e9-9169-e8796056e1f3.png)
The `http` URLs return as before.

**Comment by jakubgs** [comment]
Where the hell does this data come from? These URLs must be stored somewhere, but where?!

**Comment by jakubgs** [comment]
It's interesting how some of the entries don't use `http://dev.dap.ps/` but `http://localhost:4000`:
![dapp_http_localhost](https://user-images.githubusercontent.com/2212681/62642839-957d1d80-b914-11e9-918a-c82261f5bc7c.png)

**Comment by jakubgs** [comment]
I have found an interesting folder committed in `back-end/frontend`(ugh...) which contains this compiled files like:
https://github.com/dap-ps/discover/blob/master/back-end/frontend/static/js/main.ccc6a9d0.chunk.js
Which contains this:
```javascript
function(e){
  e.exports = {
    UPLOAD:"http://dev.dap.ps:8081/metadata",
    UPDATE:"http://dev.dap.ps:8081/metadata/update",
    APPROVE:"http://dev.dap.ps:8081/metadata/approve/email",
    RETRIEVE_METADATA:"http://dev.dap.ps:8081/metadata",
    RETRIEVE_ALL_METADATA:"http://dev.dap.ps:8081/metadata/all"
  }
```
I do not know WHY someone thought committing this file to the repo was a good idea, but here we are.
There's others too:
```
 $ ls -lh back-end/frontend/static/js 
total 14M
-rw-r--r-- 1 sochan sochan 2.6M Aug  7 13:21 2.07ffa3aa.chunk.js
-rw-r--r-- 1 sochan sochan 9.6M Aug  7 13:21 2.07ffa3aa.chunk.js.map
-rw-r--r-- 1 sochan sochan 429K Aug  7 13:21 main.ccc6a9d0.chunk.js
-rw-r--r-- 1 sochan sochan 664K Aug  7 13:21 main.ccc6a9d0.chunk.js.map
-rw-r--r-- 1 sochan sochan 1.5K Aug  7 13:21 runtime~main.a8a9905a.js
-rw-r--r-- 1 sochan sochan 7.9K Aug  7 13:21 runtime~main.a8a9905a.js.map
```
Why the HELL would you commit a 9.6 MB `.map` file to your repo?!
![just NO](https://user-images.githubusercontent.com/2212681/62643710-93b45980-b916-11e9-8d14-88b03d1e8c69.gif)

**Comment by jakubgs** [comment]
Also: https://github.com/dap-ps/infra-dapps/issues/1#issuecomment-519196847

**Comment by jakubgs** [comment]
Removed those files and it works fine, but didn't fix the issue with mixed content: https://github.com/dap-ps/discover/pull/31

**Comment by jakubgs** [comment]
I also love how the `Dapps` state reducer __fetches data__ using `await Database.fetchAllDapps()`:
https://github.com/dap-ps/discover/blob/a9a1f1cfbacf6ec0b17f055f50564cdfe9e78213/src/modules/Dapps/Dapps.reducer.js#L15-L22

Essentially going against one of the thee fundamental principle of using Redux:

>To specify how the state tree is transformed by actions, you write pure reducers.
https://redux.js.org/introduction/three-principles#changes-are-made-with-pure-functions

>Its return value is the same for the same arguments (no variation with local static variables, non-local variables, mutable reference arguments or input streams from I/O devices)
https://en.wikipedia.org/wiki/Pure_function

What the fuck is this software...
![SHOOT ME](https://user-images.githubusercontent.com/2212681/62648358-a03daf80-b920-11e9-9063-bf84bc22384b.jpg)

**Comment by jakubgs** [comment]
@Perseverance @jrainville @iamonuwa @bakasura980
Can I get some help from you guys? I can't figure out where this `http://` comes from in the IndexedDB.

Could you answer some questions:

* Where is the data about existing Dapps fetched in the code?
* What generates those URLs? The backend or the frontend?

**Comment by andytudhope** [comment]
I think we can just remove the whole `frontend` folder, seems like it was committed in error to me.

**Comment by andytudhope** [comment]
I agree that it is `ugh`

**Comment by jakubgs** [comment]
So, based on a suggestion from George Spasov this might be cause by use of `req.protocol` here:
```javascript
const buildImageUrl = function (req, imageHash) {
    return `${req.protocol}://${req.headers.host}${req.originalUrl}/image/${imageHash}`;
}
```
https://github.com/dap-ps/discover/blob/3c8b8c49c79bdb5f00c577507bfc52ef06029c0f/back-end/services/dapp-image-service.js#L26-L28

Which according to the documentation __should__ respect the `X-Forwarded-Proto` header __but__ only under a specific condition:
>When the `trust proxy` setting does not evaluate to false, this property will use the value of the X-Forwarded-Proto header field if present. This header can be set by the client or by the proxy.
https://expressjs.com/en/api.html#req.protocol

**Comment by jakubgs** [comment]
So I added some log messages to that section:
```javascript
const buildImageUrl = function (req, imageHash) {
    console.log('req.protocol: ', req.protocol)
    console.log('req.headers: ', req.headers)
    return `${req.protocol}://${req.headers.host}${req.originalUrl}/image/${imageHash}`;
}
```
And tried submitting a Dapp, and this is what I got back:
```
req.protocol:  http
req.headers: { host: 'dev.dap.ps',
  'x-real-ip': '10.0.101.66',
  'x-forwarded-for': '99.37.53.62, 10.0.101.66',
  'content-length': '60699',
  accept: 'application/json',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-US,en;q=0.9',
  'content-type': 'application/json',
  origin: 'https://dev.dap.ps',
  referer: 'https://dev.dap.ps/',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'same-origin',
  'user-agent':
   'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https' }
```
Which clearly shows:
```
'x-forwarded-proto': 'https'
```

**Comment by jakubgs** [comment]
Looks like adding:
```javascript
app.set('trust proxy', 'loopback')
```
In `back-end/server.js` fixed the problem:
```log
req.protocol:  https
req.header["x-forwarded-proto"]:  https
[2019-08-08 13:32:37]-[INFO]-[DApps-Metadata-Controller]: A dapp metadata with hash [QmSPtEHAXWsJEhYCg9MbHfT5mmfwYkcUJKpiCutoMRGN2h] has been uploaded successfully
[2019-08-08 13:32:38]-[INFO]-[Base-Email]: Email with subject Uploaded DApp Metadata. Hash - QmSPtEHAXWsJEhYCg9MbHfT5mmfwYkcUJKpiCutoMRGN2h was delivered successfully
```
Fix: https://github.com/dap-ps/discover/pull/7

**Comment by jakubgs** [comment]
Though there is some kind of bug with IndexedDB, because after clearing it and refreshing it's not being populated. Weird.
